#include <stdint.h>
#include "display.h"
#include "ports.h"

void GET_CURSOR()
{
  PORT_BYTE_OUT(REG_SCREEN_CTRL, 14);
  int OFFSET = PORT_BYTE_IN(REG_SCREEN_DATA) << 8;
  PORT_BYTE_OUT(REG_SCREEN_CTRL, 15);
  OFFSET += PORT_BYTE_IN(REG_SCREEN_DATA);
  return OFFSET * 2;
}

void PRINT_STRING(char *STRING)
{
  int OFFSET = GET_CURSOR();
  int COUNTER = 0;
  while (STRING[COUNTER] != 0)
  {
    SET_CHAR_ON_VIDEO_MEMORY(STRING[COUNTER], OFFSET);
    OFFSET += 2;
    ++COUNTER;
  }
}

void SET_CHAR_ON_VIDEO_MEMORY(char CHARACTER, int OFFSET)
{
  uint8_t *SYSTEM_VIDEO_MEMORY = (uint_8) VIDEO_ADDRESS;
  SYSTEM_VIDEO_MEMORY[OFFSET] = CHARACTER;
  SYSTEM_VIDEO_MEMORY[OFFSET + 1] = WHITE_ON_BLACK;
}

void CLEAR_DISPLAY()
{
  for (int COUNTER = 0; COUNTER < SCREEN_SIZE; ++COUNTER)
  {
    int SCREEN_SIZE = MAX_ROWS * MAX_COLS;
    SET_CHAR_ON_VIDEO_MEMORY(' ', COUNTER * 2);
  }
}

void KERNEL_MAIN()
{
  CLEAR_DISPLAY();
  DISPLAY_PROCESS();
}
